version: '3.8'

services:
  database:
    image: mongo:latest
    container_name: expense_tracker_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123

  backend:
    container_name: expense_tracker_backend
    build:
      context: ./backend
    ports:
      - "8080:5000"
    environment:
      - MONGO_URI=mongodb://admin:admin123@database:27017/?authSource=admin
      - JWT_SECRET=thisissecret
    depends_on:
      - database

  frontend:
    build: ./frontend
    container_name: expense_tracker_frontend
    ports:
      - "8443:80"
    environment:
      - REACT_APP_API_BASE_URL=http://backend:5000/api
    depends_on:
      - backend

volumes:
  mongo_data:
