services:
  database:
    image: mongo
    container_name: database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
        MONGO_INITDB_ROOT_PASSWORD=admin@321
    volumes:
      - /mongodb:/data/db
    ports:
      - 27017:27017

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - 8080:5000
    environment:
      - MONGO_URI=mongodb://admin:admin@database:27017/?authSource=admin
        JWT_SECRET=thisissecret
    depends_on:
      - database

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
        - BACKEND_URL=http://backend:8080/api
    ports:
      - 80:80
    depends_on:
      - backend
